language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
env:
  - CONFIGURATION_FILE=phpunit.xml
  - CONFIGURATION_FILE=phpunit.integration.xml
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
before_script:
  - composer install --dev
  - composer require satooshi/php-coveralls:* --dev
script:
    - mkdir build
    - mkdir build/coverage
    - phpunit
after_success:
    - php vendor/bin/coveralls -v -c .coveralls.yml
notifications:
  email:
    recipients:
      - DL-PP-PHP-SDK@ebay.com
    on_success: change
